# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3243555ae31575e34c9111e7f8662def619cb28238c492f34fe81943b00bb75de8ff9ca0bab8b0a4168dabe3d85b75e924ef0b921e85c9493abfd5b77aa34c8

test:
  secret_key_base: 05c4ac75fbcf998f48ec93426cda85dfc7c2a005b3b8701a719724763f3c082946d87ba3f63e11e157a215ae3189119fb31deb10a9924de25c2cd005c01d4e1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
